name: recup_storybook
description: A new Flutter package project.
version: 0.0.11

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  skeletons: ^0.0.3
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: RecupIcons
      fonts:
        - asset: assets/recup-icon-font.ttf

topics:
  - assets
  - icons
  - ui
