part of 'themes.dart';

const _textTheme = TextTheme(
  displayLarge: TextStyle(
    fontWeight: FontWeight.w400,
    height: 64.0 / 57,
    fontSize: 57,
    letterSpacing: 0,
    fontFamily: 'Poppins',
  ),
  displayMedium: TextStyle(
    fontWeight: FontWeight.w400,
    height: 52.0 / 45,
    fontSize: 45,
    letterSpacing: 0,
    fontFamily: 'Poppins',
  ),
  displaySmall: TextStyle(
    fontWeight: FontWeight.w400,
    height: 44.0 / 36,
    fontSize: 36,
    letterSpacing: 0,
    fontFamily: 'Poppins',
  ),
  headlineLarge: TextStyle(
    fontWeight: FontWeight.w400,
    height: 40.0 / 32,
    fontSize: 32,
    letterSpacing: 0,
    fontFamily: 'Poppins',
  ),
  headlineMedium: TextStyle(
    fontWeight: FontWeight.w400,
    height: 36.0 / 28,
    fontSize: 28,
    letterSpacing: 0,
    fontFamily: 'Poppins',
  ),
  headlineSmall: TextStyle(
    fontWeight: FontWeight.w400,
    height: 32.0 / 24,
    fontSize: 24,
    letterSpacing: 0,
    fontFamily: 'Poppins',
  ),
  titleLarge: TextStyle(
    fontWeight: FontWeight.w400,
    height: 28.0 / 22,
    fontSize: 22,
    letterSpacing: 0,
    fontFamily: 'Poppins',
  ),
  titleMedium: TextStyle(
    fontWeight: FontWeight.w500,
    height: 24.0 / 16,
    fontSize: 16,
    letterSpacing: 0.15,
    fontFamily: 'Poppins',
  ),
  titleSmall: TextStyle(
    fontWeight: FontWeight.w500,
    height: 20.0 / 14.0,
    fontSize: 14,
    letterSpacing: 0.1,
    fontFamily: 'Poppins',
  ),
  labelLarge: TextStyle(
    fontFamily: 'Poppins',
    fontSize: 16,
    height: 24.0 / 16,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.15,
  ),
  labelMedium: TextStyle(
    fontFamily: 'Poppins',
    fontSize: 14,
    height: 20.0 / 14,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.1,
  ),
  labelSmall: TextStyle(
    fontFamily: 'Poppins',
    fontSize: 12,
    height: 16.0 / 12,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.5,
  ),
  bodyLarge: TextStyle(
    fontSize: 16,
    height: 24.0 / 16,
    fontWeight: FontWeight.w400,
    fontFamily: 'Poppins',
  ),
  bodyMedium: TextStyle(
    fontSize: 14,
    height: 20.0 / 14,
    fontWeight: FontWeight.w400,
    fontFamily: 'Poppins',
  ),
  bodySmall: TextStyle(
    fontSize: 12,
    height: 16.0 / 12,
    fontWeight: FontWeight.w400,
    fontFamily: 'Poppins',
  ),
);
